
server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subscribe?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    password: P@ssw0rd
    username: root
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.shiro.demoshiro